---
clickhouse_version: "22.3.3.44"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static

vector_url: "https://packages.timber.io/vector/0.23.0/vector_0.23.0-1_amd64.deb"  
